services:

  # Keycloak service definition will be inherited from concrete clustering configurations.
  acme-keycloakx:
    build:
      context: "."
      dockerfile: "./src/main/docker/Dockerfile.jvm"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    volumes:
      - ./keycloakx:/keycloakx:z
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8787:8787"

  acme-keycloak-db:
    image: postgres:11.12
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    ports:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
#    volumes:
#      - ./target/postgres/data:/var/lib/postgresql/data:z
